## YAML Template.
---
spring:    
    sleuth:
        sampler.percentage: 0.2
        web.skipPattern: (^cleanup.*)
zuul:
    routes:
        orders:            
            service-id: order-service
            path: /orders/**
            stripPrefix: true
        customers:            
            service-id: customer-service
            path: /customers/**      
            stripPrefix: true            
eureka:
    instance:
      instanceId: ${spring.application.name}:${random.value}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
