## YAML Template.
---
app.name: Product Service v2.0

eureka:
  instance:
      instanceId: ${spring.application.name}:${random.value}
      ## this should not be enabled on production
      leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
